// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(SpecificationContext))]
    partial class SpecificationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("WebApplication.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDateDeadline")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecificationModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationModelId");

                    b.ToTable("OrderModel");
                });

            modelBuilder.Entity("WebApplication.Models.SpecificationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CountForParent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasureUnit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SpecificationModels");
                });

            modelBuilder.Entity("WebApplication.Models.WarehouseRecordModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecificationModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationModelId");

                    b.ToTable("WarehouseRecordModel");
                });

            modelBuilder.Entity("WebApplication.Models.OrderModel", b =>
                {
                    b.HasOne("WebApplication.Models.SpecificationModel", "SpecificationModel")
                        .WithMany("Orders")
                        .HasForeignKey("SpecificationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationModel");
                });

            modelBuilder.Entity("WebApplication.Models.SpecificationModel", b =>
                {
                    b.HasOne("WebApplication.Models.SpecificationModel", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WebApplication.Models.WarehouseRecordModel", b =>
                {
                    b.HasOne("WebApplication.Models.SpecificationModel", "SpecificationModel")
                        .WithMany("WarehouseRecords")
                        .HasForeignKey("SpecificationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationModel");
                });

            modelBuilder.Entity("WebApplication.Models.SpecificationModel", b =>
                {
                    b.Navigation("Childrens");

                    b.Navigation("Orders");

                    b.Navigation("WarehouseRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
